mysql:
  host: localhost
  user: root
  pass: pass
  port: 3306
  db: man10offlinebank

mlendFee: 0.1
mlendMax: 10000000.0
mlendRate: 1.0
enableLocalLoan: false

loggingServerHistory: false
paymentThread: false

kickDunce: false

isInstalledShop: false

revolving:
  lendParameter: 0.0
  borrowStandardScore: 0
  minServerLoan: 100000.0
  maxServerLoan: 1000000.0
  revolvingFee: 0.0
  lastPaymentCycle: 0
  enable: true